package codeintel

import (
	"fmt"
	"path/filepath"
	"sort"
	"strings"
)

// Search finds symbols whose label contains q (case-insensitive).
func (g *Graph) Search(q string, limit int) []Node {
	var out []Node
	q = strings.ToLower(q)
	for _, n := range g.Nodes {
		if strings.Contains(strings.ToLower(n.Label), q) {
			out = append(out, n)
		}
	}
	sort.Slice(out, func(i, j int) bool { return out[i].Label < out[j].Label })
	if limit > 0 && len(out) > limit {
		out = out[:limit]
	}
	return out
}

// Symbols lists a file's nodes, sorted by source location.
func (g *Graph) Symbols(path string) []Node {
	var out []Node
	for _, n := range g.Nodes {
		if n.SourceFile == path {
			out = append(out, n)
		}
	}
	sort.Slice(out, func(i, j int) bool { return out[i].SourceLoc < out[j].SourceLoc })
	return out
}

// Callers returns the nodes that call the symbol with the given label or id.
func (g *Graph) Callers(name string) []Node {
	var out []Node
	targets := map[string]bool{}
	for _, n := range g.Nodes {
		if n.Label == name || n.ID == name {
			targets[n.ID] = true
		}
	}
	for _, e := range g.Edges {
		if e.Relation == "calls" && targets[e.Target] {
			if n, ok := g.Nodes[e.Source]; ok {
				out = append(out, n)
			}
		}
	}
	return out
}

// Callees returns the nodes the symbol calls.
func (g *Graph) Callees(name string) []Node {
	var out []Node
	srcs := map[string]bool{}
	for _, n := range g.Nodes {
		if n.Label == name || n.ID == name {
			srcs[n.ID] = true
		}
	}
	for _, e := range g.Edges {
		if e.Relation == "calls" && srcs[e.Source] {
			if n, ok := g.Nodes[e.Target]; ok {
				out = append(out, n)
			}
		}
	}
	return out
}

// GenerateMap produces the MAP.md body (ticket-05 schema): one
// "## <module>" section per top-level directory.
func (g *Graph) GenerateMap() string {
	type module struct {
		dir     string
		files   map[string]int // file → symbol count
		symbols []Node
	}
	mods := map[string]*module{}
	var order []string
	for _, n := range g.Nodes {
		if strings.Contains(n.ID, ":file:") {
			continue // file nodes are not symbols
		}
		top := topDir(n.SourceFile)
		m, ok := mods[top]
		if !ok {
			m = &module{dir: top, files: map[string]int{}}
			mods[top] = m
			order = append(order, top)
		}
		m.symbols = append(m.symbols, n)
		m.files[n.SourceFile]++
	}
	sort.Strings(order)
	var sb strings.Builder
	sb.WriteString("# MAP.md — navigation (Layer 1)\n\n")
	sb.WriteString("_Generated by code-intel (ticket 07). Schema per ticket 05 — hand-edits to the body are overwritten on regeneration._\n\n")
	for _, dir := range order {
		m := mods[dir]
		fmt.Fprintf(&sb, "## %s\n\n", m.dir)
		type fc struct {
			path string
			n    int
		}
		var files []fc
		for p, n := range m.files {
			files = append(files, fc{p, n})
		}
		sort.Slice(files, func(i, j int) bool { return files[i].n > files[j].n })
		if len(files) > 5 {
			files = files[:5]
		}
		for _, f := range files {
			fmt.Fprintf(&sb, "- `%s` (%d symbols)\n", f.path, f.n)
		}
		sort.Slice(m.symbols, func(i, j int) bool { return m.symbols[i].Label < m.symbols[j].Label })
		limit := len(m.symbols)
		if limit > 20 {
			limit = 20
		}
		sb.WriteString("\nSymbols:\n")
		for _, n := range m.symbols[:limit] {
			fmt.Fprintf(&sb, "- %s (%s)\n", n.Label, kindOf(n.ID))
		}
		sb.WriteString("\n")
	}
	return sb.String()
}

func topDir(path string) string {
	dir := filepath.ToSlash(filepath.Dir(path))
	if dir == "." || dir == "" {
		return "root"
	}
	return dir
}

func kindOf(id string) string {
	parts := strings.Split(id, ":")
	if len(parts) >= 2 {
		return parts[1]
	}
	return "?"
}
